server: "Ice" #Ros or Ice
address: "localhost"
port: "10000"
topicM: "/turtlebotROS/mobile_base/commands/velocity"
topicI: '/turtlebotROS/cameraL/image_raw'
endpointM: "setMotors"
endpointI: "setCamera"
Glacier:
  address: "localhost"
  port: "5063"
  endpoint: "DemoGlacier2/router"
